#The numbers in this config are amount of ticks. 20 ticks = 1 second; so 1 minute would be 1200
questions:
  time_between_questions: 1200
  round_length: 600

#Set this to more than -1 if you would like players to not be able to spam answers, but still be able to answer more than once
cooldown: -1

rewards:
  win_money: true
  win_amount_money: 100
  win_item: true
  #Set the type of item(MUST BE IN ALL CAPS) and the amount below
  win_amount_item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND
      amount: 1
  #If you put something in between the '', it will run your command when someone wins. Do not put the /
  #Use %player% , in place of the Player's name!
  win_command: ""
